### ISSUE TITLE
Docs looks weird at pkg.go.dev

### ISSUE THREAD

**Issue by prochac** [hellofresh/kandalf#52]
See https://pkg.go.dev/github.com/hellofresh/kandalf

**Comment by vgarvardt** [comment]
Thank you for reporting. I will take a look at this.

**Comment by prochac** [comment]
Oh, got it.
Here is missing the license
https://github.com/hellofresh/kandalf/tree/v0.2.2
That's why

**Comment by vgarvardt** [comment]
The problem is the way pkg.do.dev works - it fetches information about go libraries not from repos as godoc.org does but from public proxy. Public proxy gets information about libraries when they are downloaded with `go get ...`. Because of this pkg.do.dev has information only about the last used version of the library. Given that kandalf is not a library actually but an application and already has version 0.6.6 I guess it will never get information about its latest code.

I will just remove the link to code docs as app is not really exposing any code that worth documenting for public usage and app usage is described in its readme.

Thank you for reporting the issue.
